server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #表示是否与register结合。设置为true，通过serviceId大写来进行转发
logging:
  level:  #表示日志级别
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8082/eureka/
